services:
  journalgrabber:
    build: .
    container_name: journalgrabber
    ports:
      - "6003:5000"
    volumes:
      - ./downloads:/app/downloads
      - ./data:/app/data
    environment:
      # Environment variables (can also be set in .env file)
      # Values in .env file will take precedence over these defaults
      - FLASK_ENV=production
      - SECRET_KEY=change-this-secret-key-in-production
      - DATABASE_URL=sqlite:////app/data/journalgrabber.db
      - DOWNLOAD_PATH=/app/downloads
      - ARXIV_API_DELAY=3.0
      - DEFAULT_MAX_RESULTS=50
      - DEFAULT_SEARCH_DAYS=30
      # Zotero Integration: Set these in .env file for security
      # Do not set empty values here as they will override .env file
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
